name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          check-latest: true
          cache: true
      - name: Build
        run: go build -v
      - name: Upload backend build artifact
        uses: actions/upload-artifact@v2
        with:
          name: backend
          path: pomu
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '17'
          cache: 'yarn'
      - name: Download / Refresh dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Upload frontend build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: frontend
          path: dist/
